
package org.example.receiveclaiminfofromgvs;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ReceiveClaimInfoFromGVS", targetNamespace = "http://www.example.org/ReceiveClaimInfoFromGVS/", wsdlLocation = "file:/Users/haolin/Working/docs/690/compensation_info/ReceiveClaimInfoFromGVS(2).wsdl")
public class ReceiveClaimInfoFromGVS_Service
    extends Service
{

    private final static URL RECEIVECLAIMINFOFROMGVS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.example.receiveclaiminfofromgvs.ReceiveClaimInfoFromGVS_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.example.receiveclaiminfofromgvs.ReceiveClaimInfoFromGVS_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/Users/haolin/Working/docs/690/compensation_info/ReceiveClaimInfoFromGVS(2).wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/Users/haolin/Working/docs/690/compensation_info/ReceiveClaimInfoFromGVS(2).wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RECEIVECLAIMINFOFROMGVS_WSDL_LOCATION = url;
    }

    public ReceiveClaimInfoFromGVS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReceiveClaimInfoFromGVS_Service() {
        super(RECEIVECLAIMINFOFROMGVS_WSDL_LOCATION, new QName("http://www.example.org/ReceiveClaimInfoFromGVS/", "ReceiveClaimInfoFromGVS"));
    }

    /**
     * 
     * @return
     *     returns ReceiveClaimInfoFromGVS
     */
    @WebEndpoint(name = "ReceiveClaimInfoFromGVSSOAP")
    public ReceiveClaimInfoFromGVS getReceiveClaimInfoFromGVSSOAP() {
        return super.getPort(new QName("http://www.example.org/ReceiveClaimInfoFromGVS/", "ReceiveClaimInfoFromGVSSOAP"), ReceiveClaimInfoFromGVS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReceiveClaimInfoFromGVS
     */
    @WebEndpoint(name = "ReceiveClaimInfoFromGVSSOAP")
    public ReceiveClaimInfoFromGVS getReceiveClaimInfoFromGVSSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/ReceiveClaimInfoFromGVS/", "ReceiveClaimInfoFromGVSSOAP"), ReceiveClaimInfoFromGVS.class, features);
    }

}
