
package me.hao0.cxf.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://service.cxf.learn.haol.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param arg0
     * @return
     *     returns User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "load", targetNamespace = "http://service.cxf.learn.haol.org/", className = "Load")
    @ResponseWrapper(localName = "loadResponse", targetNamespace = "http://service.cxf.learn.haol.org/", className = "LoadResponse")
    public User load(
            @WebParam(name = "arg0", targetNamespace = "")
            Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://service.cxf.learn.haol.org/", className = "Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://service.cxf.learn.haol.org/", className = "CreateResponse")
    public boolean create(
            @WebParam(name = "arg0", targetNamespace = "")
            User arg0);

    /**
     * 
     * @return
     *     returns java.util.List<User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "list", targetNamespace = "http://service.cxf.learn.haol.org/", className = "List")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://service.cxf.learn.haol.org/", className = "ListResponse")
    public List<User> list();

}
